-- FrameNames.lua

FrameNames = {
    -- Normal frames
    { frame = "AddonList" },
    { frame = "BankFrame" },
    { frame = "BattlefieldFrame" },
    { frame = "CharacterFrame" },
    { frame = "ChatConfigFrame" },
    { frame = "ContainerFrameCombinedBags" },
    { frame = "DestinyFrame" },
    { frame = "DressUpFrame" },
    { frame = "SpellBookFrame" },
    { frame = "FriendsFrame" },
    { frame = "GameMenuFrame" },
    { frame = "GossipFrame" },
    { frame = "GuildInviteFrame" },
    { frame = "GuildRegistrarFrame" },
    { frame = "HelpFrame" },
    { frame = "InterfaceOptionsFrame" },
    { frame = "ItemTextFrame" },
    { frame = "LFGParentFrame" },
    { frame = "LootFrame" },
    { frame = "MailFrame" },
    { frame = "MerchantFrame" },
    { frame = "ModelPreviewFrame" },
    { frame = "PetitionFrame" },
    { frame = "PetStableFrame" },
    { frame = "PingSystemTutorial" },
    { frame = "PVEFrame" },
    { frame = "PVPFrame" },
    { frame = "PVPParentFrame" },
    { frame = "QuestFrame" },
    { frame = "QuestLogFrame" },
    { frame = "QuestLogDetailFrame" },
    { frame = "QuestLogPopupDetailFrame" },
    { frame = "QuickKeybindFrame" },
    { frame = "ReadyCheckFrame" },
    { frame = "RecruitAFriendRecruitmentFrame" },
    { frame = "RecruitAFriendRewardsFrame" },
    { frame = "SettingsPanel" },
    { frame = "SpellBookFrame" },
    { frame = "SplashFrame" },
    { frame = "TabardFrame" },
    { frame = "TalkingHeadFrame" },
    { frame = "TaxiFrame" },
    { frame = "TradeFrame" },
    { frame = "VideoOptionsFrame" },
    { frame = "WorldMapFrame" },
    { frame = "WorldStateScoreFrame" },
    -- Classic frames
        -- { frame = "TalentFrame" },
        -- { frame = "QuestLogFrame" },
        -- { frame = "GuildFrame" },
        -- { frame = "ArtifactFrame" },
    -- Blizzard_Addon frames
    { frame = "AchievementFrame", addon = "Blizzard_AchievementUI" },
    { frame = "AlliedRacesFrame", addon = "Blizzard_AlliedRacesUI" },
    { frame = "AnimaDiversionFrame", addon = "Blizzard_AnimaDiversionUI" },
    { frame = "ArchaeologyFrame", addon = "Blizzard_ArchaeologyUI" },
    { frame = "ArtifactFrame", addon = "Blizzard_ArtifactUI" },
    { frame = "AuctionHouseFrame", addon = "Blizzard_AuctionHouseUI" },
    { frame = "AuctionFrame", addon = "Blizzard_AuctionUI" },
    { frame = "AzeriteEssenceUI", addon = "Blizzard_AzeriteEssenceUI" },
    { frame = "AzeriteRespecFrame", addon = "Blizzard_AzeriteRespecUI" },
    { frame = "AzeriteEmpoweredItemUI", addon = "Blizzard_AzeriteUI" },
    { frame = "BarberShopFrame", addon = "Blizzard_BarbershopUI" },
    { frame = "BehavioralMessagingDetails", addon = "Blizzard_BehavioralMessaging" },
    { frame = "KeyBindingFrame", addon = "Blizzard_BindingUI" },
    { frame = "BlackMarketFrame", addon = "Blizzard_BlackMarketUI" },
    { frame = "CalendarFrame", addon = "Blizzard_Calendar" },
    { frame = "ChallengesKeystoneFrame", addon = "Blizzard_ChallengesUI" },
    { frame = "ChannelFrame", addon = "Blizzard_Channels" },
    { frame = "ChromieTimeFrame", addon = "Blizzard_ChromieTimeUI" },
    { frame = "ClassTalentFrame", addon = "Blizzard_ClassTalentUI" },
    { frame = "ClickBindingFrame", addon = "Blizzard_ClickBindingUI" },
    { frame = "CollectionsJournal", addon = "Blizzard_Collections" }, -- WardrobeFrame?
    { frame = "CommunitiesFrame", addon = "Blizzard_Communities" }, -- check these
    { frame = "ContributionCollectionFrame", addon = "Blizzard_Contribution" },
    { frame = "CovenantPreviewFrame", addon = "Blizzard_CovenantPreviewUI" },
    { frame = "CovenantRenownFrame", addon = "Blizzard_CovenantRenown" },
    { frame = "CovenantSanctumFrame", addon = "Blizzard_CovenantSanctum" },
    { frame = "CraftFrame", addon = "Blizzard_CraftUI" },
    { frame = "DeathRecapFrame", addon = "Blizzard_DeathRecap" },
    { frame = "EncounterJournal", addon = "Blizzard_EncounterJournal" },
    { frame = "ExpansionLandingPage", addon = "Blizzard_ExpansionLandingPage" },
    { frame = "FlightMapFrame", addon = "Blizzard_FlightMap" },
    { frame = "GarrisonBuildingFrame", addon = "Blizzard_GarrisonUI" },
    { frame = "GarrisonCapacitiveDisplayFrame", addon = "Blizzard_GarrisonUI" },
    { frame = "GarrisonLandingPage", addon = "Blizzard_GarrisonUI" },
    { frame = "GarrisonMissionFrame", addon = "Blizzard_GarrisonUI" },
    { frame = "GarrisonMonumentFrame", addon = "Blizzard_GarrisonUI" },
    { frame = "GarrisonRecruiterFrame", addon = "Blizzard_GarrisonUI" },
    { frame = "GarrisonRecruitSelectFrame", addon = "Blizzard_GarrisonUI" },
    { frame = "GarrisonShipyardFrame", addon = "Blizzard_GarrisonUI" },
    { frame = "OrderHallMissionFrame", addon = "Blizzard_GarrisonUI" },
    { frame = "BFAMissionFrame", addon = "Blizzard_GarrisonUI" },
    { frame = "CovenantMissionFrame", addon = "Blizzard_GarrisonUI" },
    { frame = "GenericTraitFrame", addon = "Blizzard_GenericTraitUI" },
    { frame = "PlayerTalentFrame", addon = "Blizzard_GlyphUI" },
    { frame = "GMSurveyFrame", addon = "Blizzard_GMSurveyUI" },
    { frame = "GuildBankFrame", addon = "Blizzard_GuildBankUI" },
    { frame = "GuildControlUI", addon = "Blizzard_GuildControlUI" },
    { frame = "GuildFrame", addon = "Blizzard_GuildUI" },
    { frame = "InspectFrame", addon = "Blizzard_InspectUI" },
    { frame = "IslandsPartyPoseFrame", addon = "Blizzard_IslandsPartyPoseUI" },
    { frame = "IslandsQueueFrame", addon = "Blizzard_IslandsQueueUI" },
    { frame = "TransmogrifyFrame", addon = "Blizzard_ItemAlterationUI" },
    { frame = "ItemInteractionFrame", addon = "Blizzard_ItemInteractionUI" },
    { frame = "ItemSocketingFrame", addon = "Blizzard_ItemSocketingUI" },
    { frame = "ItemUpgradeFrame", addon = "Blizzard_ItemUpgradeUI" },
    { frame = "LFGParentFrame", addon = "Blizzard_LookingForGroupUI" },
    { frame = "LookingForGuildFrame", addon = "Blizzard_LookingForGuildUI" },
    { frame = "MacroFrame", addon = "Blizzard_MacroUI" },
    { frame = "MajorFactionRenownFrame", addon = "Blizzard_MajorFactions" },
    { frame = "MatchCelebrationPartyPoseFrame", addon = "Blizzard_MatchCelebrationPartyPoseUI" },
    { frame = "ObliterumForgeFrame", addon = "Blizzard_ObliterumUI" },
    { frame = "OrderHallTalentFrame", addon = "Blizzard_OrderHallUI" },
    { frame = "PlayerChoiceFrame", addon = "Blizzard_PlayerChoiceUI" },
    { frame = "PlayerSpellsFrame", addon = "Blizzard_PlayerSpells" },
    { frame = "InspectRecipeFrame", addon = "Blizzard_Professions" },
    { frame = "ProfessionsFrame", addon = "Blizzard_Professions" },
    { frame = "ProfessionsCustomerOrdersFrame", addon = "Blizzard_ProfessionsCustomerOrders" },
    { frame = "PVPMatchResults", addon = "Blizzard_PVPMatch" },
    { frame = "PVPMatchScoreboard", addon = "Blizzard_PVPUI" },
    { frame = "ReforgingFrame", addon = "Blizzard_ReforgingUI" },
    { frame = "RuneforgeFrame", addon = "Blizzard_RuneforgeUI" },
    { frame = "ScrappingMachineFrame", addon = "Blizzard_ScrappingMachineUI" },
    { frame = "SoulbindViewer", addon = "Blizzard_Soulbinds" },
    { frame = "StableFrame", addon = "Blizzard_StableUI" },
    { frame = "SubscriptionInterstitialFrame", addon = "Blizzard_SubscriptionInterstitialUI" },
    { frame = "TalentFrame", addon = "Blizzard_TalentUI" },
    { frame = "PlayerTalentFrame", addon = "Blizzard_TalentUI" },
    { frame = "TalkingHeadFrame", addon = "Blizzard_TalkingHeadUI" },
    { frame = "TimeManagerFrame", addon = "Blizzard_TimeManager" },
    { frame = "TorghastLevelPickerFrame", addon = "Blizzard_TorghastLevelPicker" },
    { frame = "TradeSkillFrame", addon = "Blizzard_TradeSkillUI" },
    { frame = "ClassTrainerFrame", addon = "Blizzard_TrainerUI" },
    { frame = "UIWidgetBelowMinimapContainerFrame", addon = "Blizzard_UIWidgets" },
    { frame = "UIWidgetPowerBarContainerFrame", addon = "Blizzard_UIWidgets" },
    { frame = "UIWidgetTopCenterContainerFrame", addon = "Blizzard_UIWidgets" },
    { frame = "VoidStorageFrame", addon = "Blizzard_VoidStorageUI" },
    { frame = "WarboardQuestChoiceFrame", addon = "Blizzard_WarboardUI" },
    { frame = "WarfrontsPartyPoseFrame", addon = "Blizzard_WarfrontsPartyPoseUI" },
    { frame = "WeeklyRewardsFrame", addon = "Blizzard_WeeklyRewards" },
    -- { frame = "", addon = "Blizzard_" },
}

-- -- Addon frames
-- AddonFrames = {
--     ["Blizzard_AchievementUI"] = "AchievementFrame",
-- }

-- { frame = "TradeSkillFrame" },
-- { frame = "AuctionFrame" },
-- { frame = "MailFrame" },
-- { frame = "BankFrame" },
-- { frame = "MerchantFrame" },
-- { frame = "WorldMapFrame" },
-- { frame = "LootFrame" },
-- { frame = "PVPFrame" },
-- { frame = "EncounterJournal" },
-- { frame = "CollectionsJournal" },
-- { frame = "GarrisonLandingPage" },
-- { frame = "OrderHallCommandBar" },
-- { frame = "CommunitiesFrame" },
-- { frame = "PetJournal" },
-- { frame = "ToyBox" },
-- { frame = "HeirloomsJournal" },
-- { frame = "WardrobeFrame" },